apiVersion: batch/v1
kind: Job       # We are testing the Job resource type
metadata:
  name: ml-job  # A name must be given to the Job type in the metadata section
spec: 
  #replicas: 1
  #selector:
    #matchLabels:
      #app: mlconsumer                    # This is the specification where we can even put the number of replicas
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: ml        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      containers:
      - name: ml       # this is going to be used for DNS name
        image: 192.168.1.64:5000/mlconsumer  # this is the image in registry accessible
                                             # from all our workers
    #     volumeMounts:
    #     - mountPath: .
    #       name: consumed

        imagePullPolicy: Always  # This forces the node to pull the image
        command: ["python"]
        args: ["consumer.py"] 
      restartPolicy: Never
  #minReadySeconds: 5
    #   volumes:
    #   - name: consumed
    # # mount /data/foo, but only if that directory already exists
    #   hostPath:
    #     path: /producer_data/ # directory location on host
    #     type: Directory # this field is optional 
        
      